### ISSUE TITLE
doesnt work anymore

### ISSUE THREAD

**Issue by zoff99** [fscarmen/warp-on-actions#2]
```
Preparing to unpack .../cloudflare-warp_2024.9.346.0_amd64.deb ...
Unpacking cloudflare-warp (2024.9.346.0) ...
Setting up nftables (0.9.3-2) ...
Setting up desktop-file-utils (0.24-1ubuntu3) ...
Setting up libnss3-tools (2:3.98-0ubuntu0.20.04.2) ...
Setting up cloudflare-warp (2024.9.346.0) ...
Created symlink /etc/systemd/system/multi-user.target.wants/warp-svc.service → /lib/systemd/system/warp-svc.service.
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Success
Success
error: unrecognized subcommand 'add-excluded-route'

Usage: warp-cli [OPTIONS] <COMMAND>

For more information, try '--help'.
```

**Comment by zoff99** [comment]
as issue on ubuntu 22.04 runner

**Comment by fscarmen3** [comment]
try v1.0 instead
```
  - name: Set up WARP
    uses: fscarmen/warp-on-actions@v1.0
    with:
      mode: wireguard
```

**Comment by zoff99** [comment]
can it set ipv6? because thats what i need

**Comment by fscarmen3** [comment]
Yes，both IPv4 and IPv6.

**Comment by fscarmen** [comment]
Yes，both IPv4 and IPv6.

**Comment by zoff99** [comment]
ok nice. it does work. what about the newer version? do you still update this repo?

**Comment by fscarmen** [comment]
Please update to v1.2

https://github.com/fscarmen/warp-on-actions/actions/runs/11274928602

```
  - name: Set up WARP
    uses: fscarmen/warp-on-actions@v1.2
    with:
      stack: dual   # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
```
